name: Test ssh
on:
  push:
    branches: develop
env:
  WEB_FOLDER: /var/www/onecoffee-web-demo
  IMAGE_NAME: bravo680/onecoffee-web
  IMAGE_TAG: latest
jobs:
  Test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -tt -o StrictHostKeyChecking=no -i key.pem $SSH_USER@$SSH_HOST \
          "export IMAGE_NAME=$IMAGE_NAME IMAGE_TAG=$IMAGE_TAG WEB_FOLDER=$WEB_FOLDER && \
          cd $WEB_FOLDER && \
          if [ -f docker-compose.yaml ]; then \
            echo \"docker-compose.yml exists, proceeding with deployment.\" && \
            docker compose down && \
            docker rmi -f $IMAGE_NAME:$IMAGE_TAG && \
            docker pull $IMAGE_NAME:$IMAGE_TAG && \
            docker compose up -d; \
          else \
            echo \"docker-compose.yaml not found in $WEB_FOLDER\" && \
            exit 1; \
          fi"
