name: CI/CD
run-name: CI/CD ONe coffee web
on:
  pull_request:
    branches:
      - main
jobs:
  Run-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 20  
      - name: Install dependencies & lint
        run: |
          yarn
          yarn lint
    continue-on-error: false
  Build-docker-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build docker image
        run: |
          docker build -t bravo680/onecoffee-web:latest .
      - name: Login to docker hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to docker hub
        run: docker push bravo680/onecoffee-web:latest
