name: Lint and Build
run-name: Lint and Build
on:
  pull_request:
    branches:
      - main
jobs:
  Run-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 20  
      - name: Install dependencies & lint
        run: |
          yarn
          yarn lint
    continue-on-error: false
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 20  
      - name: Install dependencies & build
        env:
          BASE_URL: ${{ APP_BASE_URL }}
          NEXT_PUBLIC_GG_CLIENT_ID: ${{ APP_NEXT_PUBLIC_GG_CLIENT_ID }}
          ADMIN_DOMAIN: ${{ APP_ADMIN_DOMAIN }}
          HOST: ${{ APP_HOST }}
        run: |
          yarn
          yarn build
      
