name: Run eslint
run-name: ${{ github.actor }} is running eslint ğŸš€
on:
  push:
    branches:
      - develop
jobs:
  Run-eslint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start linting"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 20
      - run: echo "ğŸ Set up node successfully"
      - run: yarn
      - run: yarn lint
