name: Lint and Build
run-name: Lint and Build
on:
  pull_request:
    branches:
      - main
jobs:
  Run-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 20  
      - name: Install dependencies & lint
        run: |
          yarn
          yarn lint
    continue-on-error: false
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 20  
      - name: Install dependencies & build
        run: |
          yarn
          export BASE_URL=http://localhost:3000
          yarn build
      
