name: Test notify
on:
  push:
    branches: develop

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Notify to telegram
        uses: ./.github/actions/notify
        with:
          status: ${{ job.status }}
          project: test
          token: ${{ secrets.TELE_TOKEN }}
          to: ${{ secrets.TELE_CHANNEL_ID }}
